server:
  port: 8080
  servlet:
    context-path: /news

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root2
    password: 123456
    url: jdbc:mysql://localhost:3307/test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
